Adding HomeWork1
boOhdan/AltexSoftLab pull request #1
Opened 2021-04-12 10:40 UTC by boOhdan

2021-04-12 11:25 UTC, serhii-shkodenko requested changes
В целом выглядит хорошо. Имена поправь пока, вечером еще раз гляну.

2021-04-12 11:25 UTC, serhii-shkodenko commented on HomeWork1/HomeWork1/HomeWork.cs
> +            // Your solution supposed to be here.
Этот комментарий можно удалить. Он был оставлен, чтобы сориентировать, где стоит начать выполнение.

2021-04-12 11:25 UTC, serhii-shkodenko commented on HomeWork1/HomeWork1/HomeWork.cs
> +            // Your solution supposed to be here.
Этот комментарий тоже можно удалить.

2021-04-12 11:25 UTC, serhii-shkodenko commented on HomeWork1/HomeWork1/HomeWork.cs
> +        public string getStreet(string destinations)
Согласно конвенциям, методы в C# называются в PascalCase. Подробнее об этом можно [почитать здесь](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions).

2021-04-12 11:25 UTC, serhii-shkodenko commented on HomeWork1/HomeWork1/HomeWork.cs
> +            string[] _destinations = destinations.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)[0]
Локальные переменные в C# называют в camelCase, знак подчеркивания допускается, а в некторых командах и приветствуется, для имен полей.

2021-04-12 11:25 UTC, serhii-shkodenko commented on HomeWork1/HomeWork1/HomeWork.cs
> +            var _prices = prices.ToArray();
Локальные переменные в C# называют в camelCase, знак подчеркивания допускается, а в некторых командах и приветствуется, для имен полей.

2021-04-13 05:32 UTC, boOhdan commented
Виправив імена, видалив коментарі

2021-04-13 19:11 UTC, serhii-shkodenko requested changes
Ще одне маленьке зауваження.

2021-04-13 19:11 UTC, serhii-shkodenko commented on HomeWork1/HomeWork1/HomeWork.cs
> +            if (pricesArray.Length != currenciesArray.Length || currenciesArray.Length != clientsArray.Length)
У перевірку також варто додати `destinations`.

2021-04-13 20:26 UTC, serhii-shkodenko requested changes
Виглядає добре. Мержіть.

2021-04-13 20:27 UTC, serhii-shkodenko approved these changes

2021-04-13 20:30 UTC, merged