created caching
boOhdan/AltexSoftLab pull request #10
Opened 2021-06-11 09:04 UTC by boOhdan

2021-06-11 09:08 UTC, boOhdan commented
Привіт, можеш глянути чи правильно зробив?

2021-06-13 22:05 UTC, serhii-shkodenko requested changes
Реалізація кешу хороша, але треба поправити дещо.

2021-06-13 22:05 UTC, serhii-shkodenko commented on HomeWork3/Contracts/ICache.cs
> +        public TValue GetOrCreate(TKey key, Func<TKey, TValue> createElement);
Модифікатори `public` в інтерфейсах не вказуються, усі члени інтерфесів за замовучуванням публічні. Поприбирай їх, будь ласка.

2021-06-13 22:05 UTC, serhii-shkodenko commented on HomeWork3/Program.cs
> +            var productCache = new Cache<int, Product>();
Можуть краще `productsCache`, у множині, бо виходить, що кеш лише для одного продукту.

2021-06-13 22:05 UTC, serhii-shkodenko commented on HomeWork3/Services/Cache.cs
> +        {
Тут варто також застосувати блокування. Бо між визначенням останнього елемента і його видаленням є певний час, за який у словник може бути щось додане/видалене.

2021-06-13 22:05 UTC, serhii-shkodenko commented on HomeWork3/Services/Cache.cs
> +        public bool IsCacheFull()
Якщо ти не використовуєш цей метод ніде більше, варто його прбирати і на 25 рядку виокристоувати щось типу `if(_cache.Count == _sizeLimit)`.

2021-06-13 22:05 UTC, serhii-shkodenko commented on HomeWork3/Services/ProductService.cs
> +            return _productsStore.Products.First(product => product.Id == id);
Ти не можеш бути впевнений, що там опиниться элемент з таким Id, тому краще `FirstOrDefault()`.

2021-06-13 22:05 UTC, serhii-shkodenko commented on HomeWork3/Services/ProductService.cs
> +            return _productsStore.Products.Count();
В тебе там колекція, тож варто використовувати її властивість `Count`, а не метод з LINQ.

2021-06-13 22:05 UTC, serhii-shkodenko commented on HomeWork3/UI/OrderSystem.cs
> +                orderItems = orderItems.Append(new OrderItem(_productCache.GetOrCreate(productNumber, _productService.GetProductById), quantity));
Краще підключити кеш десь на рівні бізнес логіки, шар UI не повинен знати звідки ти береш дані, чи з кешу, чи ще звідкись. Тому підкорегуй це, будь ласка.

2021-08-30 23:30 UTC, serhii-shkodenko approved these changes
Виглядаэ добре, можна мержити.

2021-08-31 07:12 UTC, merged