created last_task8
boOhdan/AltexSoftLab pull request #11
Opened 2021-06-13 17:32 UTC by boOhdan

2021-06-14 14:39 UTC, serhii-shkodenko requested changes
Рев ще не закінчив, поки можна правити оце.

2021-06-14 14:39 UTC, serhii-shkodenko commented on HomeWork3/Models/ExchangeRate.cs
> +        public string baseCurrency { get; set; }
Имена свойств именуются в `PascalCase`. Поправь, пожалуйста, для всего класса.

2021-06-14 14:39 UTC, serhii-shkodenko commented on HomeWork3/Models/ExchangeRate.cs
> +            return String.Format("baseCurrency: {0}; currency: {1}; saleRateNB: {2}, purchaseRateNB: {3}; saleRate: {4}; purchaseRate: {5}",
Используй `alias` для типа.

2021-06-14 14:39 UTC, serhii-shkodenko commented on HomeWork3/Models/ExchangeRateInfo.cs
> +        public string date { get; set; }
Имена свойств именуются в `PascalCase`. Поправь, пожалуйста, для всего класса.

2021-06-14 14:39 UTC, serhii-shkodenko commented on HomeWork3/Program.cs
> +        static async Task Main(string[] args)
Додай, будь ласка, модификатор доступу.

2021-06-14 14:39 UTC, serhii-shkodenko commented on HomeWork3/Services/ExchangeRateService.cs
> +    public class ExchangeRateService
Було б чудово впроавидит для класу інтерфейс і потім інжектити його у конструктор одного з твого класів у бізнес шарі.

2021-06-14 14:39 UTC, serhii-shkodenko commented on HomeWork3/Services/OrderExtension.cs
> +    public class OrderExtension
Слово розширення додається для класів,що містять методи розширення, тому прибери його тут з назви.

2021-06-14 21:05 UTC, boOhdan commented on HomeWork3/Services/OrderExtension.cs
> +    public class OrderExtension
Змінив на OrderService, а чим є необхідність в такому класі?, чи краще якщо я додам до класу-моделі Order метод GetFullPrice()

2021-08-30 23:35 UTC, serhii-shkodenko requested changes
Поправ оце і буде апрув.

2021-08-30 23:35 UTC, serhii-shkodenko commented on HomeWork3/Services/OrderService.cs
> +    public class OrderService
Цей класс тобі не потрібний, просто додай у модель GetFullPrice() метод. Цей клас, будь ласка, видали.

2021-08-31 10:05 UTC, serhii-shkodenko approved these changes
Виглядає добре, можна мержити.

2021-08-31 10:33 UTC, merged