my home work №3
boOhdan/AltexSoftLab pull request #3
Opened 2021-04-27 14:37 UTC by boOhdan

2021-04-27 15:21 UTC, serhii-shkodenko requested changes

2021-04-27 15:21 UTC, serhii-shkodenko commented on HomeWork3/Contracts/IProductService.cs
> +        public ProductsStore ProductsStore { get; set; }
Модификатор `public` в интерфейсе является избыточном. Его можно удалить из всех методов/свойств в интерфейсах по всему ПР.

2021-04-27 15:21 UTC, serhii-shkodenko commented on HomeWork3/Models/Business.cs
> +    class Business
Не хватает модификатора доступа.

2021-04-27 15:21 UTC, serhii-shkodenko commented on HomeWork3/Date/ProductsStore.cs
> +            Products = new List<Product>()
Лучше заполнить хранилище какими-то тестовыми данными в каком-то отдельном методе, который можно вызывать в нужный момент, а не прямо в дефолтном конструкторе.

2021-04-27 15:21 UTC, serhii-shkodenko commented on HomeWork3/Services/ProductService.cs
> +        public ProductService(ProductsStore products)
Нарушение Dependency inversion principle. Лучше использовать интерфейсы.

2021-04-27 15:21 UTC, serhii-shkodenko commented on HomeWork3/Services/ProductService.cs
> +        public ProductsStore ProductsStore { get; set; }
Это свойство лучше переписать в приватное `readonly` поле, к которому обращаться из методов.

2021-04-27 15:21 UTC, serhii-shkodenko commented on HomeWork3/Services/ValidationService.cs
> +        public ValidationService(ProductsStore products)
Нарушение Dependency inversion principle. Лучше использовать интерфейсы.

2021-04-27 15:21 UTC, serhii-shkodenko commented on HomeWork3/Services/ValidationService.cs
> +        public ProductsStore ProductsStore { get; set; }
Это свойство лучше переписать в приватное `readonly` поле, к которому обращаться из методов.

2021-04-27 21:32 UTC, boOhdan commented on HomeWork3/Services/ProductService.cs
> +        public ProductsStore ProductsStore { get; set; }
А у мене там методи AddProduct, DeleteProduct змінюють значення цього свойства

2021-04-27 21:39 UTC, serhii-shkodenko commented on HomeWork3/Services/ProductService.cs
> +        public ProductsStore ProductsStore { get; set; }
Ці методи змінюють не властивість, а дані, які надає об'єкт, записаний у властивість. Тому приватне поле нічого не змінює у цьому плані.

2021-05-01 21:00 UTC, boOhdan commented
Все ок?

2021-05-01 21:03 UTC, serhii-shkodenko requested changes

2021-05-01 21:03 UTC, serhii-shkodenko commented on HomeWork3/Models/Order.cs
> +        public bool AddOrderItem(OrderItem orderItem)
Этот метод не нужен, так как сеттер свойства `OrderItems`, позволяет сделать то же самое.

2021-05-01 22:10 UTC, serhii-shkodenko requested changes
Загалом добре. Лише поправити деякі моменти.

2021-05-01 22:10 UTC, serhii-shkodenko commented on HomeWork3/Date/ProductsStore.cs
> +namespace FoodOrdering.Date
Одрук у неймспейсі. `Date` це дата, `Data` - дані.

2021-05-01 22:10 UTC, serhii-shkodenko commented on HomeWork3/UI/OrderSystem.cs
> +                switch(Int32.Parse(MessageService.ReceiveMessage()))
Відповідно до одного з останніх стандартів мови C# краще використовувати аліас типу, а не його CLR назву. Це стосується не тількит типу `int`, а будь-якого простого типу. Для Int32 це буде `int`. Переправ, будь ласка, у всьому ПР.

2021-05-01 22:10 UTC, serhii-shkodenko commented on HomeWork3/UI/OrderSystem.cs
> +                switch(Int32.Parse(MessageService.ReceiveMessage()))
Тут стається виключення, якщо натиснути у діалозі Enter, не обираючи перед тим цифру.

2021-05-01 22:10 UTC, serhii-shkodenko commented on HomeWork3/Program.cs
> +            ProductsStore productsStore = new ProductsStore();
На англійській локалі операційної системи текст у програмі виклядає так:
![Screenshot 2021-05-02 004748](https://user-images.githubusercontent.com/69808191/116795837-70fda780-aae0-11eb-9b8d-87f41de2b34c.jpg)

Треба встановити для консолі відповідне кодування.

2021-05-01 22:10 UTC, serhii-shkodenko commented on HomeWork3/UI/OrderSystem.cs
> +        public IProductService ProductService { get; set; }
Ця властивість має бути приватним `readonly` полем.

2021-05-01 22:10 UTC, serhii-shkodenko commented on HomeWork3/UI/OrderSystem.cs
> +        public IMessageService MessageService { get; set; }
Ця властивість має бути приватним `readonly` полем.

2021-05-01 22:10 UTC, serhii-shkodenko commented on HomeWork3/UI/OrderSystem.cs
> +        public IValidationService ValidationService { get; set; }
Ця властивість має бути приватним `readonly` полем.

2021-05-01 22:10 UTC, serhii-shkodenko commented on HomeWork3/UI/OrderSystem.cs
> +        public string Name { get; set; }
Ця властивість має бути приватним `readonly` полем.

2021-05-01 22:10 UTC, serhii-shkodenko commented on HomeWork3/Services/ProductService.cs
> +            return _productsStore.Products = _productsStore.Products.Append(product);
Це присвоювання не потрібне, бо метод `Append` повертає нову послідовність і так.

2021-05-01 22:11 UTC, serhii-shkodenko commented
Поправиш вищезгадані зауваження і буде апрув.

2021-05-05 20:22 UTC, boOhdan commented on HomeWork3/Services/ProductService.cs
> +            return _productsStore.Products = _productsStore.Products.Append(product);
Без присвоєня типу так:

return _productsStore.Products.Append(product);

У мене тоді незмінюється _productsStore.Products і продукт нікуди недодається.

2021-05-05 21:02 UTC, serhii-shkodenko commented on HomeWork3/Services/ProductService.cs
> +            return _productsStore.Products = _productsStore.Products.Append(product);
Все правильно. Ти правий, метод `Append()` хоч і повертає нову колекцію, але її треба самому присвоювати. Загалом, у твоєму сховищі `ProductsStore` властивість `Products` краще зробити з типом не `IEnumerable<Product>`, а `IList<Product>`, або `ICollection<Product>`.

2021-05-05 21:04 UTC, serhii-shkodenko commented
Виглядає добре. Можна мержити.

2021-05-05 21:04 UTC, serhii-shkodenko approved these changes, later dismissed
Виглядає добре. Можна мержити.

2021-05-05 21:48 UTC, boOhdan commented
Пише що Review required, Merging is blocked

2021-05-05 21:52 UTC, serhii-shkodenko requested changes

2021-05-05 21:52 UTC, serhii-shkodenko commented on HomeWork3/Data/ProductsStore.cs
> +        public ICollection<Product> AddDefaultElements()
Цей об'єкт, що повертається, ніде не використовується, тож буде достатньо повертати із методу `void`. Тоді присвоювання дефолтних значень можна зробити простіше:
```
Products.Add(new Product("Toast", "Toast...", 12, ProductType.Breads, 5));
...
```

2021-05-05 21:53 UTC, serhii-shkodenko commented
> Пише що Review required, Merging is blocked

Так і має бути. Нові коміти скидають аппрув.

2021-05-05 22:04 UTC, serhii-shkodenko approved these changes
Виглядає добре. Можна мержити.

2021-05-05 22:08 UTC, merged