Task №7, logging requests to the file
boOhdan/AltexSoftLab pull request #5
Opened 2021-05-19 15:38 UTC by boOhdan

2021-05-19 15:56 UTC, boOhdan commented
Як буде краше так:
Append<T>(T element, OperationType operationStatus)
чи так:
Append(string element, OperationType operationStatus) і передавати в element - обєкт.ToString()

2021-05-20 19:53 UTC, boOhdan commented
Я хочу подати наступне завдання, то мені треба вібранчитись від цієї вітки створивши наприклад task8 і можна пушити наступне завдання?

2021-05-20 20:13 UTC, serhii-shkodenko commented
> Я хочу подати наступне завдання, то мені треба вібранчитись від цієї вітки створивши наприклад task8 і можна пушити наступне завдання?

Тут логер тільки, ти не залежиш від нього у наступному завданні, тому ти можеш нову гліку створити, відбранчувавшись від головної.

2021-05-20 20:14 UTC, serhii-shkodenko commented
> Як буде краще так:
> Append(T element, OperationType operationStatus)
> чи так:
> Append(string element, OperationType operationStatus) і передавати в element - обєкт.ToString()

Перший варіант мені видається кращим.

2021-05-20 20:31 UTC, serhii-shkodenko requested changes

2021-05-20 20:31 UTC, serhii-shkodenko commented on HomeWork3/Services/Logger.cs
> +        private string FileDirectory { get; set; }
Властивості призначені аби бути загальнодоступними, або доступними для спадкоємців. Але тут потрібне по своїй природі щось приватне, бо шлях куди зберігати інформацію - це деталь реалізаціі, і вона має бути схована від інших. Тому напрям думки є обгрунтованим. Треба лише замінити приватну властивість на приватне `readonly` поле.

2021-05-20 20:31 UTC, serhii-shkodenko commented on HomeWork3/Services/Logger.cs
> +            var fileName = DateTime.Now.ToString("dddd, dd MMMM yyyy") + ".txt";
Твоя дата будет виглядати так:
![date_formatted](https://user-images.githubusercontent.com/69808191/119044313-b8ca6d00-b9c2-11eb-83c6-8d5a69fcc518.jpg)

Тобто назва файлу буде мати пробіли. Загальноприйнято називати такі файли без пробілів. День тижня також не використовують. Зазвичай, буде достатньо щось на кшталт такого: "logs_10_12_2021.txt", або взагалі "logs_10122021.txt".

2021-05-20 20:59 UTC, serhii-shkodenko approved these changes
Виглядяє добре, можна мержити.

2021-05-20 21:08 UTC, merged