task 8, created json serialization
boOhdan/AltexSoftLab pull request #7
Opened 2021-05-21 05:39 UTC by boOhdan

2021-05-25 16:46 UTC, boOhdan commented
Домашнє готове до перевірки

2021-06-03 22:38 UTC, serhii-shkodenko requested changes

2021-06-03 22:38 UTC, serhii-shkodenko commented on HomeWork3/Contracts/ISerializer.cs
> +    public interface ISerializer<T>
Насправді завдання було про зберігання стану сховища. Те що там під капотом зберігаються серіалізовані дані є деталлю реалізації, про яку користуачам цього коду знати необов'язково. Тому зв'язок із серілазацією / двесериілазацією треба прибрати із назв класів, методів, інтерфейсів.

2021-06-03 22:38 UTC, serhii-shkodenko commented on HomeWork3/Services/JsonSerialization.cs
> +            _path = AppDomain.CurrentDomain.BaseDirectory + @"\" + fileName;
Властивість `AppDomain.CurrentDomain.BaseDirectory` вже має у кінці слеш / зворотній слеш (в залежності від ОС), тому немає потреби додавати це щось окрім самого ім'я файлу.

2021-06-03 22:38 UTC, serhii-shkodenko commented on HomeWork3/Services/JsonSerialization.cs
> +            using var file = new FileStream(_path, FileMode.Create);
Я думаю краще не перезаписувати файл, затираючи наявний контент, а додавати до існуючого нове.

2021-06-04 09:49 UTC, boOhdan commented on HomeWork3/Services/JsonSerialization.cs
> +            using var file = new FileStream(_path, FileMode.Create);
Ну це такий універсальний метод) не тільки для додавання, якщо ми захочемо видалити обо змінити елемет то виходить нам треба переписати весь файл і так (хоча у мене немає ще такої функціональності як видалення, зміна)

2021-06-06 15:12 UTC, serhii-shkodenko requested changes

2021-06-06 15:12 UTC, serhii-shkodenko commented on HomeWork3/Program.cs
> +            var workingWithFile = new WorkingWithFile<Product>("JsonStore.json");
Лучше вынести имя файла в какую-нибуть константу, что бы не оперировать магическими строками.

2021-06-06 15:12 UTC, serhii-shkodenko commented on HomeWork3/Program.cs
> +            ProductsStore productsStore = new ProductsStore(workingWithFile);
Используй `var`.

2021-06-06 15:12 UTC, serhii-shkodenko commented on HomeWork3/Services/WorkingWithFile.cs
> +            using var file = new FileStream(_path, FileMode.OpenOrCreate);
Сначала лучше проверить, что файл существует по указанному пути.

2021-06-06 15:12 UTC, serhii-shkodenko commented on HomeWork3/Services/WorkingWithFile.cs
> +            return item != "" ? JsonSerializer.Deserialize<IEnumerable<T>>(item) : new List<T>();
Чтобы не аллоцировать объект в куче, лучше использовать в таких случаях `Array.Empty<T>()`.

2021-06-06 15:12 UTC, serhii-shkodenko commented on HomeWork3/Services/WorkingWithFile.cs
> +            return item != "" ? JsonSerializer.Deserialize<IEnumerable<T>>(item) : new List<T>();
Проверку лучше усложить до `string.IsNullOrEmpty(stream.ReadToEnd())`.

2021-06-10 14:28 UTC, boOhdan commented
У мене проблема, я створив для наступного завдання нову гілку task9 (так git checkout -b task9) створив коміт з виконаним завданням, але коли хочу запушити у мене в пулреквесті появляються коміти з попереднього пулреквесту, через що таке могло статися?

2021-06-10 14:44 UTC, serhii-shkodenko commented
> У мене проблема, я створив для наступного завдання нову гілку task9 (так git checkout -b task9) створив коміт з виконаним завданням, але коли хочу запушити у мене в пулреквесті появляються коміти з попереднього пулреквесту, через що таке могло статися?

Треба брачуватися від головної гілки. Ймовірно, твоя поточна гілка, коли ти робив бранчу для task9, - new_task8.

2021-06-10 14:49 UTC, boOhdan commented
Добре, Дякую попробую

2021-06-10 18:28 UTC, boOhdan commented
Я замітив що у мене завдання наступне залежить від даного, то як мені правильно створити відку для наступного завдання?

2021-06-10 18:32 UTC, serhii-shkodenko commented
> Я замітив що у мене завдання наступне залежить від даного, то як мені правильно створити вітку для наступного завдання?

Сьоме завдання полягає в створенні кешу. Це завдання - про зберігання даних. Вони не залежать один від одного.

2021-06-10 18:55 UTC, boOhdan commented
Сложно, я робив кешування на основі попереднього завдання і воно у мене залежить трохи, а можете мені перевірити це завдання і я без проблем закину наступне?

2021-06-11 20:49 UTC, serhii-shkodenko requested changes

2021-06-11 20:49 UTC, serhii-shkodenko commented on HomeWork3/Program.cs
> +            var filePath = "JsonStore.json";
Цю змінну краще винести в IWorkingWithFile в якості публічної властивості лише с активним геттером.

2021-06-11 21:23 UTC, boOhdan commented on HomeWork3/Program.cs
> +            var filePath = "JsonStore.json";
у мене в класі WorkingWithFile є поле _path, то мені ще створити окрему властивість для назви файлу наприклад FileName?

2021-06-11 21:26 UTC, serhii-shkodenko commented on HomeWork3/Program.cs
> +            var filePath = "JsonStore.json";
> у мене в класі WorkingWithFile є поле _path, то мені ще створити окрему властивість для назви файлу наприклад FileName?

Саме так.

2021-06-11 21:37 UTC, boOhdan commented on HomeWork3/Program.cs
> +            var filePath = "JsonStore.json";
Готово

2021-06-11 21:45 UTC, serhii-shkodenko approved these changes
Виглядає добре. Можна мержити.

2021-06-11 21:45 UTC, merged